const CartTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_ITEM: 'CLEAR_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CHANGE_ALL_ITEMS:'CHANGE_ALL_ITEMS'
}

export default CartTypes;